### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ui' of undefined

### ISSUE THREAD

**Issue by romancin** [nelu/rutorrent-filemanager#1]
Hi! I am trying to update to the new plugins in my docker image. If I access filemanager plugin directly to the port, it works fine, but when using reverse proxy I get this error:

[15.12.2019 12:50:23] JS error: [https://mydomain.com/rutorrent/ : 2977] Uncaught TypeError: Cannot read property 'ui' of undefined

Using the old plugin it works fine.

What can be happening here?

Thank you!

**Comment by nelu** [comment]
Looks like an error from share / media plugins (since those  have this in config "mydomain"). Try disabling those to see if the error persists, this way you can identify the broken plugin, so the issue gets created on the right project page. 
NOTE: The old plugins (from the bundle repo) dont work with the new filemanager
Will post the docker setup im using the following days .

**Comment by romancin** [comment]
I am trying only with filemanager and the problem persists:
![image](https://user-images.githubusercontent.com/17579835/70864294-15656500-1f51-11ea-9ab5-f946d78ac23b.png)

**Comment by nelu** [comment]
any settings from previous plugin version? make sure you wipe all rutorrent/share data

**Comment by nelu** [comment]
just pushed a Dockerfile sample

**Comment by romancin** [comment]
> any settings from previous plugin version? make sure you wipe all rutorrent/share (settings,cache, etc)data, also look at the debugger, specifically the network tab, and look for any errors, since this seems to be a proxy issue, from your description

Related to filemanager, in the Network tab I see this error:

Request URL: https://mydomain.com/plugins/filemanager/js/twig.min.js
Request Method: GET
Status Code: 404 
Remote Address: 192.168.1.25:443
Referrer Policy: no-referrer-when-downgrade

I am accessing it by mydomain.com/rutorrent, but in this URL /rutorrent doesn't appear. This seems to be the problem. Is this URL configurable in filemanager?

Thank you for your fast responses!

**Comment by nelu** [comment]
should be now fixed in master. using plugin.path -> #4df37e5c0877ad7b0ca5d6e5646e93c65acb695a

**Comment by romancin** [comment]
Wow! Thank you really much! Jenkins is building now.

**Comment by nelu** [comment]
use this as docker build context:  
` image: ${SERVICE_IMAGE}
    build:
      context: ./src
      dockerfile: ./plugins/filemanager/Dockerfile
` for now, till i publish the whole docker-compose project

**Comment by romancin** [comment]
I am using my own image based on Alpine, I make a clone of your repo in the Dockerfile. I confirm new commit works correctly. Thank you very much for your help!
