### ISSUE TITLE
pressing filemanager refresh button sorts parent dir (../) at the bottom

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [nelu/rutorrent-filemanager#10]
Using today's master.

1. choose any sort order (e.g. name up) -> ../ is at the top, as expected
2. press refresh -> ../ is at the bottom
3. navigate to a different folder by clicking ../ or another folder's name -> ../ at the bottom
4. change sort order -> ../ is at the top
5. jump to 2 or 3, at the bottom again

**Comment by nelu** [comment]
Just gave it a try using the current master branch, and the parent directory entry  - "../" is always on the first row, in subdirectories

Does it still reproduce for you?
