### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by raverdave-2k** [nelu/rutorrent-filemanager#11]
As I was having a problem with the output of Media Info via the File Manager plugin not being selectable I decided to try and use the latest version to see if it was something that had already been fixed.

I have cloned the repo, emptied out the "plugins\filemanager" directory and copied the downloaded content there, and chowned it all to www-data:www-data, however on refreshing rutorrent I get:

"Bad response from server: (500 [error,getplugins]) Internal Server Error"

**Comment by nelu** [comment]
Contents from error logs from webserver?
