### ISSUE TITLE
Filemanager fails to browse directory

### ISSUE THREAD

**Issue by Merlincool** [nelu/rutorrent-filemanager#12]
I am using headless ubuntu server, installed rtorrent on ngnix server.

Filemanager got installed correctly and I could see directories but thats just it, it cannot further browse or go into any directories. it says -  No such file/dir - /home/USER/rtorrent / Permission Denied.

I am sure directory do exists and I was using this filemanager and it was working flawless https://github.com/artyuum/Filemanager-install-script-for-ruTorrent.

I was trying your filemanager so I could also use fileshare plugin but filemanager by you seems not to work well.

**Comment by nelu** [comment]
Hi, 

Unfortunatly the old version of filemanager used in https://github.com/artyuum/Filemanager-install-script-for-ruTorrent is no longer supported
