### ISSUE TITLE
Filemanager is broken in rutorrent master branch

### ISSUE THREAD

**Issue by Whisper40** [nelu/rutorrent-filemanager#15]
Filemanager was working properly, but actually with master branch it cannot list directories
Error : Could not retrieve directory -> Échec de la récupération du contenu du dossier. - /
-> https://github.com/Novik/ruTorrent/issues/2258

**Comment by nelu** [comment]
Is might be related to this https://github.com/nelu/rutorrent-filemanager/pull/14 ?

**Comment by stickz** [comment]
> Is might be related to this #14 ?

Yes it is related to that.

**Comment by nelu** [comment]
The fixes which @stickz provided are now on the master branch of the repo. 
Please feel free to report other issues, if any
