### ISSUE TITLE
Filemanager not loading ?

### ISSUE THREAD

**Issue by Whisper40** [nelu/rutorrent-filemanager#17]
Hello, we installed today your plugin on master branch, but the plugin is not loading, empty results 
![image](https://user-images.githubusercontent.com/30440458/149839475-c2ff0287-9373-4296-8f2e-3a98b15875d1.png)

Tested with this commit : https://github.com/Novik/ruTorrent/commit/fc9d1f070e3af0b0f329c0c9f4838c0dafba21a8

**Comment by nelu** [comment]
Hi, thanks for the feedback. 
Do you see any error in the browser debugger -> Network section (filter by "filemanager")?

**Comment by Whisper40** [comment]
No error in network section, no error in console, no error in rutorrent container

**Comment by Whisper40** [comment]
When clicking on "filemanager" tab it shows in the console this : "   valled frm bootstrap format  "

->  "console.log('valled frm bootstrap format');"

**Comment by nelu** [comment]
Looks like the language translation does not get loaded properly. Can you try english as language to see if it fixes the issue.
Is it possible to access your test environment / ruTorrrent setup, to see what might be the issue in your setup?

**Comment by Whisper40** [comment]
You are right it is a translation problem, in english it's ok
I have this error ( but this one is on my side for sure ) 
![image](https://user-images.githubusercontent.com/30440458/149840727-050ae064-2584-46bc-9daa-411c1a6f2d88.png)

I can give you access through teamviewer if needed

**Comment by nelu** [comment]
Ok, glad we found the issue. Looks like [fr.js](https://github.com/nelu/rutorrent-filemanager/blob/master/lang/fr.js) (and other) translations files need some updates with new strings, according to https://github.com/nelu/rutorrent-filemanager/blob/master/lang/en.js

**Comment by Whisper40** [comment]
I can help if needed for the french translation, let me know

**Comment by nelu** [comment]
It would be great if you can create a pull request with the proper translations for french lang
