### ISSUE TITLE
Tab not showing

### ISSUE THREAD

**Issue by lordvalium** [nelu/rutorrent-filemanager#2]
Hi, installed the plugin in under rutorrent/plugins/
Plugin has been loaded and enabled. 
But Tab for filemanager is not shown. 

Reloaded browser-window.. but no effect.

**Comment by nelu** [comment]
any errors in debugger, console/network tab?

**Comment by lordvalium** [comment]
Hi, 
the hint with the prefix fixed the first step. thank you. 
Did not know that i have to remove it. 

Now i see the tab :)

But no content. 
![image](https://user-images.githubusercontent.com/2970225/71560388-8f294280-2a69-11ea-9dca-faac0d988204.png)


Console log is also empty.

**Comment by Magicalex** [comment]
Same issue on my side.

**Comment by nelu** [comment]
Possible that $topDirectory var has the default value  ("/") try changing that if its the case. also check the context menu in the "Files" tab, see if Filemanager is present there

**Comment by Magicalex** [comment]
@nelu I find a message error

```
[29.12.19 18:56:13] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>execute.capture</methodName><params>
<param><value><string></string></value></param>
<param><value><string>/rutorrent/app/plugins/filemanager/src/../scripts/sucmd.sh</string></value></param>
<param><value><string>find '/data/downloads' -mindepth 1 -maxdepth 1 -printf '%y\t%f\t%s\t%C@\t%#m\n'  2&gt;&amp;1</string></value></param>
</params></methodCall>
[29.12.19 18:56:13] Status: 200 OK
Content-Type: text/xml
Content-Length: 296

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Bad return code.</string></value></member>
</struct></value>
</fault>
</methodResponse>

[29.12.19 18:56:55] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>execute.capture</methodName><params>
<param><value><string></string></value></param>
<param><value><string>/rutorrent/app/plugins/filemanager/src/../scripts/sucmd.sh</string></value></param>
<param><value><string>find '/data/downloads' -mindepth 1 -maxdepth 1 -printf '%y\t%f\t%s\t%C@\t%#m\n'  2&gt;&amp;1</string></value></param>
</params></methodCall>
[29.12.19 18:56:55] Status: 200 OK
Content-Type: text/xml
Content-Length: 296

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Bad return code.</string></value></member>
</struct></value>
</fault>
</methodResponse>
```

**Comment by lordvalium** [comment]
@Magicalex where do you fetch that logs?

**Comment by nelu** [comment]
Try chmod 775 /rutorrent/app/plugins/filemanager/src/../scripts/sucmd.sh

**Comment by lordvalium** [comment]
There is no file "sucmd.sh" in https://github.com/nelu/rutorrent-filemanager/tree/master/src

**Comment by Magicalex** [comment]
@lordvalium in `$log_file = '/tmp/errors.log'` log file of rutorrent

@nelu still the same issue with chmod 775 :(

**Comment by lordvalium** [comment]
> Possible that $topDirectory var has the default value ("/") try changing that. also check the context menu in the "Files" tab, see if Filemanager is present there for torrent files. Also check the rutorrent settings dialog, see if Filemanager pane is present

- rutorrent settings dialog - Filemanager **is** present
- context menu in Files tab - its present there, but when i select a file in the files tab the created torren from the file is defect.

**Comment by Magicalex** [comment]
@nelu can you use sh instead bash? bash isn't installed on my docker image.

```
#!/usr/bin/env sh

cmd=$(echo $*);
sh -c "$cmd" 2>&1;

echo "{\"exitcode\":$?}";
exit 0;
```

**Comment by nelu** [comment]
So that fixes your issues i suppose?

**Comment by lordvalium** [comment]
Hi @nelu i have tried the idea from @Magicalex . Substitute "bash" with "sh" but no success. 
Same Situation unfortunately.

**Comment by nelu** [comment]
@lordvalium - the fast fix in this case is to install bash

**Comment by nelu** [comment]
use this docker-compose project https://github.com/nelu/rutorrent-dock and image https://hub.docker.com/repository/docker/unzel/rutorrent-filemanager

**Comment by lordvalium** [comment]
So i shall delete better my [linuxserver/rutorrent](https://github.com/linuxserver/docker-rutorrent)?

On my current bash is installed: 

root@linuxserver-rutorrent1:/bin# bash --version
GNU bash, version 5.0.0(1)-release (x86_64-alpine-linux-musl)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@linuxserver-rutorrent1:/bin#

**Comment by nelu** [comment]
yeah. use my build to see how it works. also look in src/Docker file from https://github.com/nelu/rutorrent-dock to see how it was setup. also you can run it from there

**Comment by lordvalium** [comment]
I could also try it by just pulling from that url here: 

![image](https://user-images.githubusercontent.com/2970225/71597522-cc620300-2b43-11ea-9a17-bbfc5a17f8ec.png)

**Comment by lordvalium** [comment]
Thank you for your engagement, but your docker container is not running out of the box. It says no connection to rtorrent and issues with thte SCGI_PORT.

I would rather try so solve that with[ that container ](https://github.com/linuxserver/docker-rutorrent) because i have also configured him a lot. 
Or could i transfer all the settings?

**Comment by nelu** [comment]
You need to clone & run the whole docker-compose repo (https://github.com/nelu/rutorrent-dock) or you need to ask the image maintainer of linuxserver/rutorrent to use the latest version of filemanager

**Comment by lordvalium** [comment]
I will give it a try. 
Just struggling to bring it up: 

[fox@monster:~/rutorrent-dock$ docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
fox@monster:~/rutorrent-dock$ sudo docker-compose up
Recreating rutorrent-dock_web_1 ... error

ERROR: for rutorrent-dock_web_1  Cannot start service web: driver failed programming external connectivity on endpoint rutorrent-dock_web_1 (a774604965da856b3726fcbb72ec06f64d6eef686a2456e64d75d8d2314ba01a): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint rutorrent-dock_web_1 (a774604965da856b3726fcbb72ec06f64d6eef686a2456e64d75d8d2314ba01a): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
fox@monster:~/rutorrent-dock$
](url)

**Comment by lordvalium** [comment]
@Magicalex  is the issue also solved for you?
As this is a plugin it seems to have still an issue, either if its sh or bash or?

@nelu  can you please reopen it. The docker you provided is a possible workaround, thank you. 
But the original issue is not solved or?

**Comment by Merlincool** [comment]
Dont know if this is limited exclusively for docker? I am using headless server ubuntu 18 LTS and I cant see filemanager tab, I tried removing "rutorrent-" prefix, still not working
