### ISSUE TITLE
Migration to 7ZIP

### ISSUE THREAD

**Issue by Whisper40** [nelu/rutorrent-filemanager#26]
Error message -> theUILang.fErrMsg[24]

Hi, you have just migrated to 7zip, I am coming to you as I have tried to apply the change on our side (with your master branch) but I have an error.
We are using an alpine image, I installed the "p7zip" package then configured the config.php like this 

`apk add p7zip`  -> https://pkgs.alpinelinux.org/contents?branch=edge&name=p7zip&arch=x86_64&repo=main
```

<?php

global $pathToExternals;
// set with fullpath to binary or leave empty
// $pathToExternals['rar'] = '';
$pathToExternals['7zip'] = '/usr/bin/p7zip';              //////////// HERE

$config['mkdperm'] = 755; // default permission to set to new created directories
$config['show_fullpaths'] = false; // wheter to show userpaths or full system paths in the UI

$config['textExtensions'] = 'log|txt|nfo|sfv|xml|html';

// see what 7zip extraction supports as type by file extension
$config['fileExtractExtensions'] = '7z|bzip2|t?bz2|t?g|gz[ip]?|iso|img|lzma|rar|tar|t?xz|zip|z01|wim';

// archive creation, see archiver man page before editing
// archive.fileExt -> config
$config['archive']['type'] = [
    '7z' => [
        'bin' =>'7z',
        'compression' => [0, 5, 9],
    ],
    // 'rar' => [
    //     'bin' =>'rar',
    //     'compression' => range(0, 5),
    // ]
  ];

$config['archive']['type']['zip'] = $config['archive']['type']['7z'];
$config['archive']['type']['tar'] = $config['archive']['type']['7z'];
$config['archive']['type']['gzip'] = $config['archive']['type']['7z'];
$config['archive']['type']['tgz'] = $config['archive']['type']['7z'];
$config['archive']['type']['tar.bz2'] = $config['archive']['type']['7z'];
$config['archive']['type']['bzip2'] = $config['archive']['type']['7z'];

```
Thanks for help 

Issue on our side : https://github.com/mondediefr/docker-rutorrent/issues/48

**Comment by nelu** [comment]
See if:
 - removing 7z from this line https://github.com/nelu/rutorrent-filemanager/blob/df9232cb3e1889b21718b245d2bff2d09d8aa02a/plugin.info#L6 will help
 -  or make a simlink for `7z` from /usr/bin/p7zip and afterwards 
If option 1 fixes the issue, i will commit the changes

**Comment by Micdu70** [comment]
`$pathToExternals['7zip'] = '/usr/bin/7z';` should be good after installing the "p7zip" alpine package.

**Comment by stickz** [comment]
@nelu the way you implemented this will not be compatible with many Linux operating systems. What you can do by default is call the `p7zip` wrapper. Look for this binary instead and use this `web.external.error` instead of `7z`.

**Comment by Whisper40** [comment]
@Micdu70 Not working, no error
(trying to delete a file from filemanager ->
 ![image](https://user-images.githubusercontent.com/30440458/152294258-c5211357-2412-4464-8b80-4b86fe0e158b.png) )

@nelu  Not working no error : 
![image](https://user-images.githubusercontent.com/30440458/152293278-9460dd67-784b-4901-b08d-688c4825d34f.png)

There is a new problem that was not here for sure the "2022.01.28". (tested today)
I cannot enter in a directory from the filemanager today.. (tested with [234f5f2](https://github.com/nelu/rutorrent-filemanager/commit/234f5f20841ad3d1e3c095e6c6954a875fc8a6ea) )
Cannot delete a file, throwing the error above

**Comment by Micdu70** [comment]
@Whisper40 I don't have any issue with the current master branch, everything is working fine on my Debian (bullseye) server.

**Comment by Whisper40** [comment]
@Micdu70 Try your changes from this repository (alpine) : https://github.com/mondediefr/docker-rutorrent

**Comment by stickz** [comment]
@Whisper40 I created a possible fix. Give it a try. The problem is probably because the path environment variable. I ran into similar problems on ruTorrent in the past. You just have to add this with my commit `$pathToExternals['p7zip'] = '/usr/bin/p7zip'; `.
https://github.com/stickz/rutorrent-filemanager/commit/7268a1891f46a4ce54638d7c2fc854a834a2dd83

**Comment by Whisper40** [comment]
@stickz With your PR:
Create an archive, it throws in journal :     filemanager: [object Object] ->    but the 7z file seems to be created..
Not able to go into any of the directory
![buggg](https://user-images.githubusercontent.com/30440458/152300823-3df39bbb-5ba3-4d7b-aa82-3f7a28a0e987.gif)

**Comment by stickz** [comment]
@Whisper40 There was a separate issue with this plugin on ruTorrent. Try again with this ruTorrent commit. https://github.com/Novik/ruTorrent/commit/3becce06c5ec3be40e97917e0362a0ffd525377c

**Comment by Whisper40** [comment]
@stickz  issue has been fixed by @Micdu70  here :  https://github.com/mondediefr/docker-rutorrent/pull/49
Thanks
