### ISSUE TITLE
v1.0 is broken with ruTorrent on the tag 4.0-beta1

### ISSUE THREAD

**Issue by liaralabs** [nelu/rutorrent-filemanager#30]
I know that you may or may not care about supporting beta tags, as I'm guessing you are probably following the development of master on ruTorrent. However, I've recently begun pinning to actual releases for ruTorrent in swizzin. Since the 4.0-beta is latest, this is what is currently being used.

I did some bisecting and this is the last commit that works with 4.0-beta1

234f5f20841ad3d1e3c095e6c6954a875fc8a6ea

04112ceaef2ded27c0cf301d611b53c7c0bf2749 are where the troubles begin.

I'm not sure how or why changing the plugin.info starts this error showing up, but it does

nginx log output states:

```
2022/02/13 17:35:46 [error] 22900#22900: *339 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(utility/webcontroller.php): failed to open stream: No such file or directory in /srv/rutorrent/php/util.php on line 15PHP message: PHP Fatal error:  require_once(): Failed opening required 'utility/webcontroller.php' (include_path='.:/usr/share/php') in /srv/rutorrent/php/util.php on line 15" while reading response header from upstream, client: 192.168.121.1, server: _, request: "GET /rutorrent/php/getplugins.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.121.14", referrer: "https://192.168.121.14/rutorrent/"
```

It would be nice if I could have a release to pin to from your end; however, barring all else I will simply pin filemanager to the last known working commit if the release tag matches 4.0-beta1

Some further debugging:

Adding the removed line from the plugin.info at least allows the ruTorrent web ui to load (albeit with the filemanager plugin disabled)

Installing p7zip-full breaks the entire thing again and the entire ruTorrent web ui (essentially, actually supplying the 7z bin), with or without the line.

My current workaround is to pin the repo to 234f5f20841ad3d1e3c095e6c6954a875fc8a6ea where everything seems to actually be functioning, even with p7zip-full installed. I don't know what substantial improvements were made between this tag and the v1.0 release; however, since it completely breaks the web UI at later commits, a working plugin seems to be preferred to a broken web ui.

**Comment by nelu** [comment]
Should be fixed in latest master branch.

**Comment by jaum20** [comment]
I found this error too, but don't know if it is related to this plugin:
`[error] 136647#136647: *9696 FastCGI sent in stderr: "PHP message: PHP Warning:  include_once(utility/webcontroller.php): Failed to open stream: No such file or directory in /srv/rutorrent/php/util.php on line 21`

**Comment by nelu** [comment]
Should be fine since its a warning generated by the autoloader in utils.php. it can be disabled in ruTorrent config: https://github.com/Novik/ruTorrent/blob/905a6a1c7f8e9af6a30eca8581eae533a9428448/conf/config.php#L29
