### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by TMTYD** [nelu/rutorrent-filemanager#33]
Hi

i have a PHP Error

what´s the problem ?

```
PHP Fatal error:  Uncaught Error: Class 'FileUtil' not found in /var/www/ru/plugins/filemanager/src/Helper.php:109
```
```
\nStacktrace:\n#0 /var/www/ru/plugins/filemanager/init.php(11): Flm\\Helper::getConfig()\n#1 /var/www/ru/php/getplugins.php(495):
```
```
require_once('/var/www/ru/plu...')\n#2 {main}\n  thrown in /var/www/ru/plugins/filemanager/src/Helper.php on line 109 
```

**Comment by TMTYD** [comment]
here is the line 190-115

```
eval(FileUtil::getPluginConf('filemanager'));

            if (!isset($config))
            {
                require_once(dirname(__FILE__) . '/../conf.php');
```

**Comment by Micdu70** [comment]
Hello,

It's mandatory to install the latest development version of ruTorrent ( via `git clone https://github.com/Novik/ruTorrent.git rutorrent` ) -OR- ruTorrent v4.0-beta.1 => https://github.com/Novik/ruTorrent/releases/tag/v4.0-beta.1

**Comment by TMTYD** [comment]
At the moment I'm using version 3.10, is it recommended to update to 4.0 beta to fix this error?

**Comment by Micdu70** [comment]
Recommended and mandatory, yes. ;)

**Comment by TMTYD** [comment]
Ok thx

**Comment by AntoineCardon** [comment]
Got the same issue,
Work for me with the same docker as you with this : https://github.com/artyuum/filemanager-install-script-for-rutorrent

**Comment by nelu** [comment]
That install script (https://github.com/artyuum/filemanager-install-script-for-rutorrent) uses the legacy version of filemanager (last updated 7 years ago) which is not supported anymore, for a while now. This repository is standalone for the filemanager plugin.
