### ISSUE TITLE
Error when creating archives

### ISSUE THREAD

**Issue by ILLYAG** [nelu/rutorrent-filemanager#36]
Creating archives gives the following error..
`Flm\Archive::getCompressBin(): Argument #1 ($type) must be of type string, null given, called in /srv/rutorrent/plugins/filemanager/src/Archive.php on line 32`

Currently using Deb11/ru v4b1 but failed on others too.

**Comment by Merlincool** [comment]
I am facing similar issue

**Comment by InsideTheMindofThePuzzledOne** [comment]
uninstall the rtx and install again. All Fixed.

**Comment by nelu** [comment]
Should be fixed in the latest commit. Can you please check and confirm its working properly?
