### ISSUE TITLE
Cannot read properties of undefined (reading 'isDirectory')

### ISSUE THREAD

**Issue by Enissay** [nelu/rutorrent-filemanager#37]
The issue happens when you want to select which files in the torrent to download/exclude.

Details shared in: https://github.com/Novik/ruTorrent/issues/2405

If I may add, the issue showed up for me when I changed the display for the files tab:
- when it was showing folders as such and you have to double click to get in, it was working fine
- when I changed it so that the full/relative path is shown: `file1`, `dir1/file1.1`, ... The error then showed up!
I would like to revert back but the menu never shows up because of the error

**Comment by nelu** [comment]
Give the latest version a try
