### ISSUE TITLE
Relative symlink patch not work

### ISSUE THREAD

**Issue by sbdvhjrfw** [nelu/rutorrent-filemanager#39]
Hello,

When there is a relative folder, it is treated as a file. If the main folder itself is pointing to a relative folder, e.g. an external HDD, it will not even see it.
How to fix it?

![Képernyőfotó 2023-04-07 - 20 57 01](https://user-images.githubusercontent.com/33731226/230662611-1410beee-6554-4c34-8ed5-a55228c0a70f.jpg)
![Képernyőfotó 2023-04-07 - 20 56 53](https://user-images.githubusercontent.com/33731226/230662618-320b610b-22d8-421a-8255-63a8a24cb980.jpg)

**Comment by nelu** [comment]
Use bind mounts instead of symlinks if you want to manage files outside of $topDirectory configured dir
