### ISSUE TITLE
filemanager suddenly stopped working

### ISSUE THREAD

**Issue by Phukit** [nelu/rutorrent-filemanager#4]
Hi,

for some reason the filemanager plugin stopped working for me.

What can I provide to help get a fix?

Thanks.

**Comment by nelu** [comment]
Any erros in console/network debug? 
Please provide more details on what doesnt work (tab doesnt show, is enabled in Plugins tab, etc)

**Comment by Phukit** [comment]
no errors in the logs.

I am running nginx server.

tab is there, plugin is enabled and loaded and everything looks like it is working but there is no directory structure for some reason.

It is a new install and when I first installed the plugin it worked like normal and now nothing for some reason.

**Comment by Phukit** [comment]
I finally figured it out.  It has been bugging me for some time now.

There was something in the browser cache that was doing this, I cleared the cache and now it is working again.
