### ISSUE TITLE
Apache Errors when filemanager plugin is loaded ..tries to include some src files from wrong directory

### ISSUE THREAD

**Issue by whiteazn** [nelu/rutorrent-filemanager#41]
ruTorrent 4.1.6
filemanager 1.0

`[proxy_fcgi:error] [pid 1234:tid 1234] [client <IP>] 
AH01071: Got error '
PHP message: PHP Warning:  include_once(utility/webcontroller.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/webcontroller.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21
PHP message: PHP Warning:  include_once(utility/basecontroller.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/basecontroller.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21
PHP message: PHP Warning:  include_once(utility/filemanager.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/filemanager.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21
PHP message: PHP Warning:  include_once(utility/filesystem.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/filesystem.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21
PHP message: PHP Warning:  include_once(utility/shellcmd.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/shellcmd.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21
PHP message: PHP Warning:  include_once(utility/remoteshell.php): failed to open stream: No such file or directory in /var/www/rutorrent/php/util.php on line 21PHP message: PHP Warning:  include_once(): Failed opening 'utility/remoteshell.php' for inclusion (include_path='.:/usr/share/php:/var/www/rutorrent/conf/:/var/www/rutorrent/php/:/var/www/rutorrent/') in /var/www/rutorrent/php/util.php on line 21', 
referer: https://<domain>/rutorrent/`

The shellcmd and remoteshell files are attempted to be included when I click on the File Manager tab in rutorrent.  

Looks like the plugin is trying to include the corresponding files in the plugins/filemanager/src directory but for some reason is looking in the /php/util/ directory instead.  

Basic functionality of the plugin still works despite the errors, but I haven't tried to do anything but basic browsing around

**Comment by nelu** [comment]
See ruTorrent [config.php](https://github.com/Novik/ruTorrent/blob/253da04e3900171a0cd5807f943d3ad4791c9cb7/conf/config.php#L29) set
`
$al_diagnostic = false
`
