### ISSUE TITLE
symbolic link and "filemanager"

### ISSUE THREAD

**Issue by Mirabeau2Code** [nelu/rutorrent-filemanager#5]
Hello,

Obviously the plugin does not like symbolic links, which are very useful under Linux

There 2 problem:

**1/ in files listing:**
     all symbolic links folders are seen as "files" (what they are but ...)

**2/  as a default folder:**
if I use a symbolic link, as the default folder on my rtorrent accounts I get this error that happens:
https://i.goopics.net/pnOZl.png

Could you tell me which php script file(s) is concerned to make this change?
thank's a lot in advance for your answer

**Comment by nelu** [comment]
The most important thing is that you need to check if ruTorrent works with symlinks.

1. is a security concern
2. as workaround you could use bind mounts for $topDirectory paths

For reference the method which handles the directory listing (listDir method) can be found here: https://github.com/nelu/rutorrent-filemanager/blob/master/src/Filesystem.php#L49
