### ISSUE TITLE
File Manager plug-in does not display all files and directories on ruTorrent 5.0

### ISSUE THREAD

**Issue by ppkhoa** [nelu/rutorrent-filemanager#52]
If you have more than 34 items (files and directories included), the list just gets cut off and does not display any items from 35th entries forward. Scrolling down further and only blank spaces can be seen.

**Comment by anthonyryan1** [comment]
The scroll issue bisects to this commit here: https://github.com/Novik/ruTorrent/commit/b93644679b432b9aa4791bcad0d7bdfdc31ef9a8

I'll report back once I understand why that's the culprit.

I believe there's a separate, different issue with the [...] button in the Move/Copy dialog as well.

**Comment by anthonyryan1** [comment]
The scrollbar problem stems from this line of CSS being removed:

```css
div#tdcont > div {height: 100%;}
```

Adding it back fixes the file manager scrolling issue.

**Comment by anthonyryan1** [comment]
And it can be fixed in a way that's specific to this plugin, without risk of changing anything else in rutorrent with:

```css
#flm-browser {
    height: 100%;
}
```

**Comment by anthonyryan1** [comment]
For the next 5.0 issue, the copy and move buttons were broken by:

https://github.com/Novik/ruTorrent/commit/3ed7cb81ea2b95a42b78c55006fdeaa618225bee

**Comment by nelu** [comment]
Thanks [anthonyryan1](https://github.com/anthonyryan1) for the quick fixes.
We are collecting the fixes for ruTorrent v5  in this temporary branch: https://github.com/nelu/rutorrent-filemanager/tree/v5-compat 
Till things get more stable, i noticed that more css needs to be ajusted to display properly with the changes on v5 (ex: dialog window icons offsets)

**Comment by nelu** [comment]
Fix of input onchange event for proper file names: https://github.com/Novik/ruTorrent/pull/2745 and triggered here: https://github.com/nelu/rutorrent-filemanager/blob/05fea019593348a180c34db3e6a1a1c62e302753/views/dialog-archive.twig#L147

**Comment by stickz** [comment]
We intend to support ruTorrent v4.3 for a while longer.  There are platforms that would like to use it with file manager. Is it possible to keep a branch for v4.3?

I'll look into getting your PR merged for v5. We are working on `v5.1` as well. We intend to drop support for `v5.0` once it's released.

**Comment by nelu** [comment]
Right now the latest release https://github.com/nelu/rutorrent-filemanager/releases/tag/v1.2 is stable and compatibile with ruTorrent v4.x and v3.x . 

The compatibility changes for ruTorrent 5.x are on separate branch for now, and wont reach master untill a stable release of ruTorrent.

**Comment by nelu** [comment]
> If you have more than 34 items (files and directories included), the list just gets cut off and does not display any items from 35th entries forward. Scrolling down further and only blank spaces can be seen.

For the time being use this branch for ruTorrent v5.x : https://github.com/nelu/rutorrent-filemanager/tree/v5-compat
