### ISSUE TITLE
Filemanager shows no path and no files, with no errors

### ISSUE THREAD

**Issue by Dan-Kouba** [nelu/rutorrent-filemanager#8]
Hello, I seem to be running into an issue with my setup of your plugin.  I have configured it (I believe) correctly, but I cannot get any files to show up in the filemanager tab in the interface.  Interestingly, no path shows up either.  I see the folder icon and the bar where the path should be, but the bar is empty.

My configuration is as follows:

- Running in this docker image: https://github.com/crazy-max/docker-rtorrent-rutorrent
- Upon initial install, I was getting the 503 error from `sucmd.sh`, but I was able to eliminate that error by switching the shell to `/bin/ash`, as bash is not available in the image I am using.  I also verified `find` is available in the image.
- `$topDirectory = '/';` is set in one of the image-provided rutorrent config files.  I want to change this but unfortunately I cannot due to how the image is set up.
- My downloads directory that I want to access is owned by the same user as rutorrent is started by.  Also, it is in the root path (`/downloads`)
- I tried setting `$config['show_fullpaths'] = true;` to see if I could get a path to show, but was unable to see a difference.
- My `conf.php` file for the plugin is as follows:

```
<?php

global $topDirectory;
global $pathToExternals;
// set with fullpath to binary or leave empty
$pathToExternals['rar'] = '/usr/bin/unrar';
$pathToExternals['zip'] = '';
$pathToExternals['unzip'] = '/usr/bin/unzip';
$pathToExternals['tar'] = '';


$config['tempdir'] = '/tmp';		// path were to store temporary data ; must be writable
$config['mkdperm'] = 755; 		// default permission to set to new created directories
$config['show_fullpaths'] = true; // wheter to show userpaths or full system paths in the UI


$config['textExtensions'] = 'txt|nfo|sfv|xml|html';
// archive mangling, see archiver man page before editing
// archive.fileExt -> config
$config['archive']['type'] = [
    'rar' => [  'bin' =>'rar',
                'compression' => range(0, 5),
    ],
    'zip' => [
        'bin' =>'zip',
        'compression' => ['-0', '-1', '-9'],
        ],
    'tar' => [
        'bin' =>'tar',
        'compression' => [0, 'gzip', 'bzip2'],
    ]
];
```

I thought this was a permissions issue, but the fact that I don't even see `/` in the path bar in the interface tells me something deeper may be going on.

Any help you can provide in debugging this?  It's probably something simple I have missed.

**Comment by nelu** [comment]
Give this a try https://github.com/nelu/rutorrent-dock . That image might use old code. Check the browser network debugger and look for filemanager requests that fail

**Comment by Dan-Kouba** [comment]
Appreciate the alternative image.  I'd ideally like it to work in the current one for a few reasons, but that's a backup option.

I checked in the network debugger and everything is returning 200's.  When I click the tab, I get this response: `action: {"method":"listDirectory","dir":null}`.  

Any other debugging I may be able to try?  Is there any additional logging I can turn on for the plugin?

**Comment by kayg04** [comment]
@Dan-Kouba: `apk add --no-cache findutils`

**Comment by LastReaction** [comment]
I'm guessing no one has a solution to this problem? I'm experiencing the same issue. When I click on the File Manager tab, the network console brings up this error message: 

```
{errcode: 10, status: "ERROR", msg: "Internal error"}
errcode: 10
msg: "Internal error"
status: "ERROR"
```

I've tried changing the $topDirectory in rutorrents config.php and setting [show_fullpaths] to true, but no luck. I'm currently using linuxserver's rutorrent docker container, and I'd rather not have to switch to another docker due to my current setup.

**Comment by janstuemmel** [comment]
I am using the [linuxserver/rutorrent](https://hub.docker.com/r/linuxserver/rutorrent/) image. Editing `$config['tempdir']` in `filemanager/conf.php` fixed the problem for me:

```diff php
// filememanger/conf.php
- $config['tempdir'] = '/tmp'; 
+ $config['tempdir'] = '/config/rutorrent/profiles/tmp';
```

https://github.com/linuxserver/docker-rutorrent/issues/127

**Comment by Koubiacz** [comment]
Hello,

Same problem for me

**Comment by Nicodemus75** [comment]
I had the same problem, but I ran across the following reddit post:

https://old.reddit.com/r/seedboxes/comments/gok7pt/empty_folder_in_filemanager/

The OP in that reddit thread solved his own problem, which also worked for me:

"...set rar, zip, unzip and tar fullpath in conf.php, they are not optional."

While this workaround solves the no path/no files/no errors problem, this still shouldn't be the case so there is some underlying problem which nelu doesn't seem to be aware of given his advice above.

**Comment by nelu** [comment]
see this on how get a simple setup running : https://github.com/nelu/rutorrent-dock/blob/master/src/Dockerfile
