### ISSUE TITLE
file operations fail

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [nelu/rutorrent-filemanager#9]
Hi,

Edit: restructured the post

First of all, thank you for creating the filemanager plugin, it's enormously helpful.

I've been using the old version (3rd-party plugins) for a long time, and it worked good enough. Recently I've upgraded the whole bunch, Ubuntu, rtorrent, rutorrent and this plugin to the latest versions, and now I'm having some trouble with both old and new versions. Software versions: ubuntu 20.04, php 7.4, rtorrent 0.9.8, rutorrent stable 3.10, filemanager master from yesterday.

1. The old version used to be able to do everything before the upgrade. Now, it can delete files, create/remove directories, but the compress/extract scripts don't work, meaning I can set up the options and start the operation, and it completes without an error, but no new archive is created and no file is extracted. Permissions/ownership is set up properly, as per description and what I found online, and as it used to work. Tool paths in config either set or left blank, same behaviour.

2. The new (this) version fails to do even that much: file deletion, directory creation, archive operations don't work at all. Possibly, none of the operations work apart from browsing the directory tree.

a) I'm getting an error in rutorrent log when trying to delete files/folders with filemanager:

    filemanager: {"response":[{"readyState":4,"responseText":"<br />\n<b>Warning</b>: file_put_contents(/tmp/.rutorrent/.fman/seedbox15935739596/task): failed to open stream: No such file or directory in <b>/var/www/rutorrent/plugins/filemanager/src/Filesystem.php</b> on line <b>127</b><br />\n{\"error\":0,\"tmpdir\":\"seedbox15935739596\"}","status":200,"statusText":"OK"},"parsererror",{}]}

The path to Filesystem.php is correct and the file exists, so that shouldn't be the problem.

One of the file removal operations I tried had this output on the task tab:

    PHP Warning:  file_get_contents(/tmp/.rutorrent/.fman/seedbox159357391819/task): failed to open stream: No such file or directory in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 13
    PHP Notice:  Trying to get property 'temp' of non-object in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 15
    PHP Notice:  Trying to get property 'dir' of non-object in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 15
    PHP Notice:  Trying to get property 'action' of non-object in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 35
    PHP Notice:  Trying to get property 'temp' of non-object in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 31
    PHP Notice:  Trying to get property 'dir' of non-object in /var/www/rutorrent/plugins/filemanager/src/TaskController.php on line 31

The location of TaskController.php is correct, though.

b) Logged error for a compress operation:

    filemanager: {"response":[{"readyState":4,"responseText":"<br />\n<b>Notice</b>: Trying to access array offset on value of type bool in <b>/var/www/rutorrent/plugins/_task/task.php</b> on line <b>78</b><br />\n{\"error\":0,\"tmpdir\":{\"no\":\"15935766765efc0ce43a49d6.61963016\",\"pid\":35281,\"status\":0,\"log\":[\"cd '\\/'\",\"\"],\"errors\":[],\"params\":{\"requester\":\"filemanager\",\"name\":\"compress\",\"arg\":\"1 files in \\/o\"},\"start\":1593576676,\"finish\":1593576676}}","status":200,"statusText":"OK"},"parsererror",{}]}

Task panel shows result OK, task details show only cd '/'.

c) I've tried to extract an archive and that didn't work either.

I'd appreciate if you helped me make this work.

Update:

Found this possible related line in the apache2 error.log file after attempting a compress operation:

    [php7:notice] [pid xxx] [client xxx] PHP Notice:  Only variables should be passed by reference in /var/www/rutorrent/plugins/filemanager/flm.class.php on line 104, referer: https://xxx/rutorrent/

**Comment by nelu** [comment]
Hi

Thank you for your feedback, the code has been developed and tested on php 7.1.31, try downgrading to that version or smth similiar 7.1.x and see if if fixes your issues.
In the new version most of the tasks are async, using the rtask plugin, meaning that the compress/extract output can be viewed in the Tasks tab of ruTorrent to get more info to diagnose those operations can be found there.


Also check that both php and rtorrent user can write /tmp/.rutorrent/.fman/

**Comment by zEdS15B3GCwq** [comment]
Hi, thanks for replying to my post.

At this point, I'm not going to revert back to php 7.1.x, as I am still able to use the old filemanager; I'll keep hoping that you'll get around updating this plugin for a more current version of php.

As for the current state of filemanager, I'm bumping into several inconveniences, such as $topDirectory in conf.php doesn't seem to have an effect; ordering of directory contents puts parent dir (../) on the bottom of the list (reported in another thread) and several other small issues. The output of the tasks tab is not very informative: see my initial post regarding compress operations.

In any case, I do hope you'll find the time to update this plugin.

**Comment by nelu** [comment]
Hi, I just tested on php 7.4 and works without any issues. See the docker image being used in  https://github.com/nelu/rutorrent-dock/blob/master/src/Dockerfile
You can try using the latest code in master branch
